const $=s=>document.querySelector(s),minutes=$('#minutes'),seconds=$('#seconds'),ring=$('#ring'),statusEl=$('#status'),done=$('#done'),app=document.querySelector('.app'),startBtn=$('#start'),startText=$('#startText'),startIcon=$('#startIcon'),alertAudio=$('#restxAlertAudio');
const R=132,C=2*Math.PI*R;ring.style.strokeDasharray=C;let selected=60,remaining=60,running=false,last=0,raf=0,audioCtx=null,installPrompt=null;
function format(v){v=Math.max(0,Math.ceil(v));minutes.textContent=String(Math.floor(v/60)).padStart(2,'0');seconds.textContent=String(v%60).padStart(2,'0')}
function render(){format(remaining);ring.style.strokeDashoffset=C*(1-(selected?remaining/selected:0));statusEl.textContent=running?'DESCANSANDO':'PRONTO'}
function state(){startBtn.disabled=running;startText.textContent='Iniciar';startIcon.innerHTML='<path d="m9 5 10 7-10 7V5Z"/>'}
function unlockAudio(){try{if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();if(alertAudio){alertAudio.volume=.001;let p=alertAudio.play();if(p&&p.then)p.then(()=>{alertAudio.pause();alertAudio.currentTime=0}).catch(()=>{})}}catch(e){}}
function fallback(){try{unlockAudio();if(!audioCtx)return;let n=audioCtx.currentTime;[{s:0,d:.42,f:880},{s:.48,d:.42,f:1046},{s:.96,d:.82,f:1318}].forEach(p=>{let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='square';o.frequency.setValueAtTime(p.f,n+p.s);g.gain.setValueAtTime(.0001,n+p.s);g.gain.linearRampToValueAtTime(.85,n+p.s+.015);g.gain.setValueAtTime(.85,n+p.s+p.d-.055);g.gain.linearRampToValueAtTime(.0001,n+p.s+p.d);o.connect(g);g.connect(audioCtx.destination);o.start(n+p.s);o.stop(n+p.s+p.d+.02)})}catch(e){}}
function beep(){try{if(alertAudio){alertAudio.pause();alertAudio.currentTime=0;alertAudio.volume=1;let p=alertAudio.play();if(p&&p.catch)p.catch(fallback)}else fallback();if(navigator.vibrate)navigator.vibrate([400,100,400,100,700])}catch(e){fallback()}}
function start(){if(running)return;if(remaining<=0)remaining=selected;unlockAudio();running=true;last=performance.now();done.classList.remove('show');app.classList.remove('finished');state();render();raf=requestAnimationFrame(tick)}
function reset(){running=false;cancelAnimationFrame(raf);remaining=selected;done.classList.remove('show');app.classList.remove('finished');state();render()}
function choose(v){selected=v;remaining=v;running=false;cancelAnimationFrame(raf);document.querySelectorAll('.preset').forEach(b=>b.classList.toggle('active',+b.dataset.time===v));done.classList.remove('show');app.classList.remove('finished');state();render()}
function adjust(d){choose(Math.min(3600,Math.max(5,selected+d)))}
function finish(){running=false;remaining=0;cancelAnimationFrame(raf);render();state();app.classList.add('finished');done.classList.add('show');beep();setTimeout(()=>{remaining=selected;render();done.classList.remove('show');app.classList.remove('finished')},2800)}
function tick(t){if(!running)return;remaining-=(t-last)/1000;last=t;if(remaining<=0){finish();return}render();raf=requestAnimationFrame(tick)}
$('#start').onclick=start;$('#reset').onclick=reset;$('#minus').onclick=()=>adjust(-5);$('#plus').onclick=()=>adjust(5);document.querySelectorAll('.preset').forEach(b=>b.onclick=()=>choose(+b.dataset.time));
addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#installBtn').hidden=true}};
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));state();render();